services:
  remirror:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/remirror
    develop:
      watch:
        - path: main.go
          action: rebuild
        - path: misc.go
          action: rebuild
        - path: go.mod
          action: rebuild
        - path: go.sum
          action: rebuild
        - path: Dockerfile
          action: rebuild
        - path: remirror.hcl
          action: rebuild
